language : python
cache: pip

sudo: true

addons:
    chrome: stable

services:
  - docker

python:
  - "3.6"

matrix:
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install node
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install webviz_components webviz_plotly
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install -r tests/requirements.txt
  - wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD

script:
  - pip install .
  - pycodestyle webviz_config
  - pytest tests
